[2025-01-17T18:05:01.155+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-17T18:05:01.173+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: DAG_ELT_PostgreSQL.join_trans manual__2025-01-17T18:04:55.465260+00:00 [queued]>
[2025-01-17T18:05:01.180+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: DAG_ELT_PostgreSQL.join_trans manual__2025-01-17T18:04:55.465260+00:00 [queued]>
[2025-01-17T18:05:01.180+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-17T18:05:01.193+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): join_trans> on 2025-01-17 18:04:55.465260+00:00
[2025-01-17T18:05:01.201+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=3066) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-17T18:05:01.203+0000] {standard_task_runner.py:72} INFO - Started process 3068 to run task
[2025-01-17T18:05:01.204+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'DAG_ELT_PostgreSQL', 'join_trans', 'manual__2025-01-17T18:04:55.465260+00:00', '--job-id', '29', '--raw', '--subdir', 'DAGS_FOLDER/ETL_PostgreSQL.py', '--cfg-path', '/tmp/tmp20adrxfq']
[2025-01-17T18:05:01.205+0000] {standard_task_runner.py:105} INFO - Job 29: Subtask join_trans
[2025-01-17T18:05:01.245+0000] {task_command.py:467} INFO - Running <TaskInstance: DAG_ELT_PostgreSQL.join_trans manual__2025-01-17T18:04:55.465260+00:00 [running]> on host 59ff16f1d4fb
[2025-01-17T18:05:01.522+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Wilfrido Rondon' AIRFLOW_CTX_DAG_ID='DAG_ELT_PostgreSQL' AIRFLOW_CTX_TASK_ID='join_trans' AIRFLOW_CTX_EXECUTION_DATE='2025-01-17T18:04:55.465260+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-17T18:04:55.465260+00:00'
[2025-01-17T18:05:01.523+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-17T18:05:01.523+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-17T18:05:01.524+0000] {logging_mixin.py:190} INFO - Current task name:join_trans state:running start_date:2025-01-17 18:05:01.173920+00:00
[2025-01-17T18:05:01.524+0000] {logging_mixin.py:190} INFO - Dag name:DAG_ELT_PostgreSQL and current dag run status:running
[2025-01-17T18:05:01.524+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-17T18:05:01.529+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/ETL_PostgreSQL.py", line 35, in _join_trans
    df = df.groupby(['date', 'store'])['sales'].sum().reset_index()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 8869, in groupby
    return DataFrameGroupBy(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/groupby/groupby.py", line 1278, in __init__
    grouper, exclusions, obj = get_grouper(
                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/groupby/grouper.py", line 1009, in get_grouper
    raise KeyError(gpr)
KeyError: 'date'
[2025-01-17T18:05:01.543+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-17T18:05:01.544+0000] {logging_mixin.py:190} INFO - Task start:2025-01-17 18:05:01.173920+00:00 end:2025-01-17 18:05:01.542980+00:00 duration:0.36906
[2025-01-17T18:05:01.544+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): join_trans> dag:<DAG: DAG_ELT_PostgreSQL> dagrun:<DagRun DAG_ELT_PostgreSQL @ 2025-01-17 18:04:55.465260+00:00: manual__2025-01-17T18:04:55.465260+00:00, state:running, queued_at: 2025-01-17 18:04:55.488016+00:00. externally triggered: True>
[2025-01-17T18:05:01.544+0000] {logging_mixin.py:190} INFO - Failure caused by 'date'
[2025-01-17T18:05:01.544+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=DAG_ELT_PostgreSQL, task_id=join_trans, run_id=manual__2025-01-17T18:04:55.465260+00:00, execution_date=20250117T180455, start_date=20250117T180501, end_date=20250117T180501
[2025-01-17T18:05:01.558+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-17T18:05:01.559+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 29 for task join_trans ('date'; 3068)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/ETL_PostgreSQL.py", line 35, in _join_trans
    df = df.groupby(['date', 'store'])['sales'].sum().reset_index()
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 8869, in groupby
    return DataFrameGroupBy(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/groupby/groupby.py", line 1278, in __init__
    grouper, exclusions, obj = get_grouper(
                               ^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/groupby/grouper.py", line 1009, in get_grouper
    raise KeyError(gpr)
KeyError: 'date'
[2025-01-17T18:05:01.601+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-17T18:05:01.622+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-17T18:05:01.626+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
