[2025-01-20T19:11:02.243+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-20T19:11:02.261+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: DAG_AWS_PIPELINE.Execute_procedure_Redshift manual__2025-01-20T19:10:48.849094+00:00 [queued]>
[2025-01-20T19:11:02.270+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: DAG_AWS_PIPELINE.Execute_procedure_Redshift manual__2025-01-20T19:10:48.849094+00:00 [queued]>
[2025-01-20T19:11:02.271+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-20T19:11:02.292+0000] {taskinstance.py:2889} INFO - Executing <Task(PostgresOperator): Execute_procedure_Redshift> on 2025-01-20 19:10:48.849094+00:00
[2025-01-20T19:11:02.304+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=5191) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-20T19:11:02.306+0000] {standard_task_runner.py:72} INFO - Started process 5193 to run task
[2025-01-20T19:11:02.307+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'DAG_AWS_PIPELINE', 'Execute_procedure_Redshift', 'manual__2025-01-20T19:10:48.849094+00:00', '--job-id', '269', '--raw', '--subdir', 'DAGS_FOLDER/Ingesta_aws.py', '--cfg-path', '/tmp/tmprhfq3db1']
[2025-01-20T19:11:02.308+0000] {standard_task_runner.py:105} INFO - Job 269: Subtask Execute_procedure_Redshift
[2025-01-20T19:11:02.367+0000] {task_command.py:467} INFO - Running <TaskInstance: DAG_AWS_PIPELINE.Execute_procedure_Redshift manual__2025-01-20T19:10:48.849094+00:00 [running]> on host 59ff16f1d4fb
[2025-01-20T19:11:02.467+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Wilfrido Rondon' AIRFLOW_CTX_DAG_ID='DAG_AWS_PIPELINE' AIRFLOW_CTX_TASK_ID='Execute_procedure_Redshift' AIRFLOW_CTX_EXECUTION_DATE='2025-01-20T19:10:48.849094+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-20T19:10:48.849094+00:00'
[2025-01-20T19:11:02.468+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-20T19:11:02.469+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-20T19:11:02.469+0000] {logging_mixin.py:190} INFO - Current task name:Execute_procedure_Redshift state:running start_date:2025-01-20 19:11:02.261984+00:00
[2025-01-20T19:11:02.469+0000] {logging_mixin.py:190} INFO - Dag name:DAG_AWS_PIPELINE and current dag run status:running
[2025-01-20T19:11:02.470+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-20T19:11:02.470+0000] {sql.py:278} INFO - Executing: CALL public.load_data_from_s3();
[2025-01-20T19:11:02.479+0000] {base.py:84} INFO - Retrieving connection 'aws_conn'
[2025-01-20T19:11:02.489+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 279, in execute
    hook = self.get_db_hook()
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 190, in get_db_hook
    return self._hook
           ^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 995, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 168, in _hook
    raise AirflowException(
airflow.exceptions.AirflowException: You are trying to use `common-sql` with AwsGenericHook, but its provider does not support it. Please upgrade the provider to a version that supports `common-sql`. The hook class should be a subclass of `***.providers.common.sql.hooks.sql.DbApiHook`. Got AwsGenericHook Hook with class hierarchy: [<class '***.providers.amazon.aws.hooks.base_aws.AwsGenericHook'>, <class '***.hooks.base.BaseHook'>, <class '***.utils.log.logging_mixin.LoggingMixin'>, <class 'typing.Generic'>, <class 'object'>]
[2025-01-20T19:11:02.496+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-20T19:11:02.497+0000] {logging_mixin.py:190} INFO - Task start:2025-01-20 19:11:02.261984+00:00 end:2025-01-20 19:11:02.496290+00:00 duration:0.234306
[2025-01-20T19:11:02.497+0000] {logging_mixin.py:190} INFO - Task:<Task(PostgresOperator): Execute_procedure_Redshift> dag:<DAG: DAG_AWS_PIPELINE> dagrun:<DagRun DAG_AWS_PIPELINE @ 2025-01-20 19:10:48.849094+00:00: manual__2025-01-20T19:10:48.849094+00:00, state:running, queued_at: 2025-01-20 19:10:48.861989+00:00. externally triggered: True>
[2025-01-20T19:11:02.497+0000] {logging_mixin.py:190} INFO - Failure caused by You are trying to use `common-sql` with AwsGenericHook, but its provider does not support it. Please upgrade the provider to a version that supports `common-sql`. The hook class should be a subclass of `***.providers.common.sql.hooks.sql.DbApiHook`. Got AwsGenericHook Hook with class hierarchy: [<class '***.providers.amazon.aws.hooks.base_aws.AwsGenericHook'>, <class '***.hooks.base.BaseHook'>, <class '***.utils.log.logging_mixin.LoggingMixin'>, <class 'typing.Generic'>, <class 'object'>]
[2025-01-20T19:11:02.497+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=DAG_AWS_PIPELINE, task_id=Execute_procedure_Redshift, run_id=manual__2025-01-20T19:10:48.849094+00:00, execution_date=20250120T191048, start_date=20250120T191102, end_date=20250120T191102
[2025-01-20T19:11:02.510+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-20T19:11:02.511+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 269 for task Execute_procedure_Redshift (You are trying to use `common-sql` with AwsGenericHook, but its provider does not support it. Please upgrade the provider to a version that supports `common-sql`. The hook class should be a subclass of `***.providers.common.sql.hooks.sql.DbApiHook`. Got AwsGenericHook Hook with class hierarchy: [<class '***.providers.amazon.aws.hooks.base_aws.AwsGenericHook'>, <class '***.hooks.base.BaseHook'>, <class '***.utils.log.logging_mixin.LoggingMixin'>, <class 'typing.Generic'>, <class 'object'>]; 5193)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 279, in execute
    hook = self.get_db_hook()
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 190, in get_db_hook
    return self._hook
           ^^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 995, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/common/sql/operators/sql.py", line 168, in _hook
    raise AirflowException(
airflow.exceptions.AirflowException: You are trying to use `common-sql` with AwsGenericHook, but its provider does not support it. Please upgrade the provider to a version that supports `common-sql`. The hook class should be a subclass of `***.providers.common.sql.hooks.sql.DbApiHook`. Got AwsGenericHook Hook with class hierarchy: [<class '***.providers.amazon.aws.hooks.base_aws.AwsGenericHook'>, <class '***.hooks.base.BaseHook'>, <class '***.utils.log.logging_mixin.LoggingMixin'>, <class 'typing.Generic'>, <class 'object'>]
[2025-01-20T19:11:02.529+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-20T19:11:02.550+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-20T19:11:02.552+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
