[2025-01-19T22:00:22.596+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-19T22:00:22.613+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: DAG_AWS_PIPELINE.glue_sparkJob manual__2025-01-19T22:00:08.661390+00:00 [queued]>
[2025-01-19T22:00:22.795+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: DAG_AWS_PIPELINE.glue_sparkJob manual__2025-01-19T22:00:08.661390+00:00 [queued]>
[2025-01-19T22:00:22.796+0000] {taskinstance.py:2866} INFO - Starting attempt 1 of 2
[2025-01-19T22:00:22.811+0000] {taskinstance.py:2889} INFO - Executing <Task(GlueJobOperator): glue_sparkJob> on 2025-01-19 22:00:08.661390+00:00
[2025-01-19T22:00:22.821+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=9865) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-19T22:00:22.823+0000] {standard_task_runner.py:72} INFO - Started process 9867 to run task
[2025-01-19T22:00:22.823+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'DAG_AWS_PIPELINE', 'glue_sparkJob', 'manual__2025-01-19T22:00:08.661390+00:00', '--job-id', '225', '--raw', '--subdir', 'DAGS_FOLDER/Ingesta_aws.py', '--cfg-path', '/tmp/tmp1an98szd']
[2025-01-19T22:00:22.824+0000] {standard_task_runner.py:105} INFO - Job 225: Subtask glue_sparkJob
[2025-01-19T22:00:22.867+0000] {task_command.py:467} INFO - Running <TaskInstance: DAG_AWS_PIPELINE.glue_sparkJob manual__2025-01-19T22:00:08.661390+00:00 [running]> on host 59ff16f1d4fb
[2025-01-19T22:00:22.949+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Wilfrido Rondon' AIRFLOW_CTX_DAG_ID='DAG_AWS_PIPELINE' AIRFLOW_CTX_TASK_ID='glue_sparkJob' AIRFLOW_CTX_EXECUTION_DATE='2025-01-19T22:00:08.661390+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-19T22:00:08.661390+00:00'
[2025-01-19T22:00:22.950+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-19T22:00:22.950+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-19T22:00:22.950+0000] {logging_mixin.py:190} INFO - Current task name:glue_sparkJob state:running start_date:2025-01-19 22:00:22.614188+00:00
[2025-01-19T22:00:22.951+0000] {logging_mixin.py:190} INFO - Dag name:DAG_AWS_PIPELINE and current dag run status:running
[2025-01-19T22:00:22.951+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-19T22:00:22.951+0000] {glue.py:195} INFO - Initializing AWS Glue Job: aws_glue_default_job. Wait for completion: True
[2025-01-19T22:00:22.951+0000] {glue.py:369} INFO - Checking if job already exists: aws_glue_default_job
[2025-01-19T22:00:22.962+0000] {base_aws.py:603} WARNING - Unable to find AWS Connection ID 'aws_default', switching to empty.
[2025-01-19T22:00:22.963+0000] {base_aws.py:177} INFO - No connection ID provided. Fallback on boto3 credential strategy (region_name='US East (Ohio) us-east-2'). See: https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html
[2025-01-19T22:00:23.245+0000] {base_aws.py:177} INFO - No connection ID provided. Fallback on boto3 credential strategy (region_name='US East (Ohio) us-east-2'). See: https://boto3.amazonaws.com/v1/documentation/api/latest/guide/configuration.html
[2025-01-19T22:00:23.270+0000] {glue.py:191} ERROR - Failed to run aws glue job, error: Provided region_name 'US East (Ohio) us-east-2' doesn't match a supported format.
[2025-01-19T22:00:23.274+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/glue.py", line 372, in has_job
    self.conn.get_job(JobName=job_name)
    ^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 995, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/base_aws.py", line 740, in conn
    return self.get_client_type(region_name=self.region_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/base_aws.py", line 710, in get_client_type
    return session.client(
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/boto3/session.py", line 297, in client
    return self._session.create_client(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/session.py", line 924, in create_client
    region_name = self._resolve_region_name(region_name, config)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/session.py", line 1023, in _resolve_region_name
    validate_region_name(region_name)
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/utils.py", line 1318, in validate_region_name
    raise InvalidRegionError(region_name=region_name)
botocore.exceptions.InvalidRegionError: Provided region_name 'US East (Ohio) us-east-2' doesn't match a supported format.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/operators/glue.py", line 200, in execute
    glue_job_run = self.glue_job_hook.initialize_job(self.script_args, self.run_job_kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/glue.py", line 187, in initialize_job
    job_name = self.get_or_create_glue_job()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/glue.py", line 410, in get_or_create_glue_job
    if self.has_job(self.job_name):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/glue.py", line 374, in has_job
    except self.conn.exceptions.EntityNotFoundException:
           ^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 995, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/base_aws.py", line 740, in conn
    return self.get_client_type(region_name=self.region_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/base_aws.py", line 710, in get_client_type
    return session.client(
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/boto3/session.py", line 297, in client
    return self._session.create_client(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/session.py", line 924, in create_client
    region_name = self._resolve_region_name(region_name, config)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/session.py", line 1023, in _resolve_region_name
    validate_region_name(region_name)
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/utils.py", line 1318, in validate_region_name
    raise InvalidRegionError(region_name=region_name)
botocore.exceptions.InvalidRegionError: Provided region_name 'US East (Ohio) us-east-2' doesn't match a supported format.
[2025-01-19T22:00:23.299+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-19T22:00:23.300+0000] {logging_mixin.py:190} INFO - Task start:2025-01-19 22:00:22.614188+00:00 end:2025-01-19 22:00:23.299059+00:00 duration:0.684871
[2025-01-19T22:00:23.300+0000] {logging_mixin.py:190} INFO - Task:<Task(GlueJobOperator): glue_sparkJob> dag:<DAG: DAG_AWS_PIPELINE> dagrun:<DagRun DAG_AWS_PIPELINE @ 2025-01-19 22:00:08.661390+00:00: manual__2025-01-19T22:00:08.661390+00:00, state:running, queued_at: 2025-01-19 22:00:08.675608+00:00. externally triggered: True>
[2025-01-19T22:00:23.300+0000] {logging_mixin.py:190} INFO - Failure caused by Provided region_name 'US East (Ohio) us-east-2' doesn't match a supported format.
[2025-01-19T22:00:23.301+0000] {taskinstance.py:1225} INFO - Marking task as UP_FOR_RETRY. dag_id=DAG_AWS_PIPELINE, task_id=glue_sparkJob, run_id=manual__2025-01-19T22:00:08.661390+00:00, execution_date=20250119T220008, start_date=20250119T220022, end_date=20250119T220023
[2025-01-19T22:00:23.326+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-19T22:00:23.327+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 225 for task glue_sparkJob (Provided region_name 'US East (Ohio) us-east-2' doesn't match a supported format.; 9867)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/glue.py", line 372, in has_job
    self.conn.get_job(JobName=job_name)
    ^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 995, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/base_aws.py", line 740, in conn
    return self.get_client_type(region_name=self.region_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/base_aws.py", line 710, in get_client_type
    return session.client(
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/boto3/session.py", line 297, in client
    return self._session.create_client(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/session.py", line 924, in create_client
    region_name = self._resolve_region_name(region_name, config)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/session.py", line 1023, in _resolve_region_name
    validate_region_name(region_name)
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/utils.py", line 1318, in validate_region_name
    raise InvalidRegionError(region_name=region_name)
botocore.exceptions.InvalidRegionError: Provided region_name 'US East (Ohio) us-east-2' doesn't match a supported format.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/operators/glue.py", line 200, in execute
    glue_job_run = self.glue_job_hook.initialize_job(self.script_args, self.run_job_kwargs)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/glue.py", line 187, in initialize_job
    job_name = self.get_or_create_glue_job()
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/glue.py", line 410, in get_or_create_glue_job
    if self.has_job(self.job_name):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/glue.py", line 374, in has_job
    except self.conn.exceptions.EntityNotFoundException:
           ^^^^^^^^^
  File "/usr/local/lib/python3.12/functools.py", line 995, in __get__
    val = self.func(instance)
          ^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/base_aws.py", line 740, in conn
    return self.get_client_type(region_name=self.region_name)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/providers/amazon/aws/hooks/base_aws.py", line 710, in get_client_type
    return session.client(
           ^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/boto3/session.py", line 297, in client
    return self._session.create_client(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/session.py", line 924, in create_client
    region_name = self._resolve_region_name(region_name, config)
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/session.py", line 1023, in _resolve_region_name
    validate_region_name(region_name)
  File "/home/airflow/.local/lib/python3.12/site-packages/botocore/utils.py", line 1318, in validate_region_name
    raise InvalidRegionError(region_name=region_name)
botocore.exceptions.InvalidRegionError: Provided region_name 'US East (Ohio) us-east-2' doesn't match a supported format.
[2025-01-19T22:00:23.366+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-19T22:00:23.392+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-19T22:00:23.396+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
