[2025-01-17T20:57:05.985+0000] {local_task_job_runner.py:123} INFO - ::group::Pre task execution logs
[2025-01-17T20:57:06.002+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: spaceflight_data_ingest_v2.fetch_blogs manual__2025-01-17T20:51:57.103152+00:00 [queued]>
[2025-01-17T20:57:06.009+0000] {taskinstance.py:2613} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: spaceflight_data_ingest_v2.fetch_blogs manual__2025-01-17T20:51:57.103152+00:00 [queued]>
[2025-01-17T20:57:06.009+0000] {taskinstance.py:2866} INFO - Starting attempt 2 of 2
[2025-01-17T20:57:06.023+0000] {taskinstance.py:2889} INFO - Executing <Task(PythonOperator): fetch_blogs> on 2025-01-17 20:51:57.103152+00:00
[2025-01-17T20:57:06.033+0000] {warnings.py:112} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:70: DeprecationWarning: This process (pid=777) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-01-17T20:57:06.034+0000] {standard_task_runner.py:72} INFO - Started process 779 to run task
[2025-01-17T20:57:06.034+0000] {standard_task_runner.py:104} INFO - Running: ['***', 'tasks', 'run', 'spaceflight_data_ingest_v2', 'fetch_blogs', 'manual__2025-01-17T20:51:57.103152+00:00', '--job-id', '72', '--raw', '--subdir', 'DAGS_FOLDER/spaceflight_data_ingest_v2.py', '--cfg-path', '/tmp/tmphknjs9m_']
[2025-01-17T20:57:06.035+0000] {standard_task_runner.py:105} INFO - Job 72: Subtask fetch_blogs
[2025-01-17T20:57:06.076+0000] {task_command.py:467} INFO - Running <TaskInstance: spaceflight_data_ingest_v2.fetch_blogs manual__2025-01-17T20:51:57.103152+00:00 [running]> on host 59ff16f1d4fb
[2025-01-17T20:57:06.150+0000] {taskinstance.py:3132} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='spaceflight_data_ingest_v2' AIRFLOW_CTX_TASK_ID='fetch_blogs' AIRFLOW_CTX_EXECUTION_DATE='2025-01-17T20:51:57.103152+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-01-17T20:51:57.103152+00:00'
[2025-01-17T20:57:06.151+0000] {logging_mixin.py:190} INFO - Task instance is in running state
[2025-01-17T20:57:06.151+0000] {logging_mixin.py:190} INFO -  Previous state of the Task instance: queued
[2025-01-17T20:57:06.151+0000] {logging_mixin.py:190} INFO - Current task name:fetch_blogs state:running start_date:2025-01-17 20:57:06.002715+00:00
[2025-01-17T20:57:06.151+0000] {logging_mixin.py:190} INFO - Dag name:spaceflight_data_ingest_v2 and current dag run status:running
[2025-01-17T20:57:06.152+0000] {taskinstance.py:731} INFO - ::endgroup::
[2025-01-17T20:57:06.706+0000] {taskinstance.py:3311} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/spaceflight_data_ingest_v2.py", line 128, in fetch_blogs
    blogs = data['blogs']
            ~~~~^^^^^^^^^
KeyError: 'blogs'
[2025-01-17T20:57:06.716+0000] {logging_mixin.py:190} INFO - Task instance in failure state
[2025-01-17T20:57:06.717+0000] {logging_mixin.py:190} INFO - Task start:2025-01-17 20:57:06.002715+00:00 end:2025-01-17 20:57:06.716301+00:00 duration:0.713586
[2025-01-17T20:57:06.717+0000] {logging_mixin.py:190} INFO - Task:<Task(PythonOperator): fetch_blogs> dag:<DAG: spaceflight_data_ingest_v2> dagrun:<DagRun spaceflight_data_ingest_v2 @ 2025-01-17 20:51:57.103152+00:00: manual__2025-01-17T20:51:57.103152+00:00, state:running, queued_at: 2025-01-17 20:51:57.124973+00:00. externally triggered: True>
[2025-01-17T20:57:06.717+0000] {logging_mixin.py:190} INFO - Failure caused by 'blogs'
[2025-01-17T20:57:06.718+0000] {taskinstance.py:1225} INFO - Marking task as FAILED. dag_id=spaceflight_data_ingest_v2, task_id=fetch_blogs, run_id=manual__2025-01-17T20:51:57.103152+00:00, execution_date=20250117T205157, start_date=20250117T205706, end_date=20250117T205706
[2025-01-17T20:57:06.731+0000] {taskinstance.py:340} INFO - ::group::Post task execution logs
[2025-01-17T20:57:06.731+0000] {standard_task_runner.py:124} ERROR - Failed to execute job 72 for task fetch_blogs ('blogs'; 779)
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/task/task_runner/standard_task_runner.py", line 117, in _start_by_fork
    ret = args.func(args, dag=self.dag)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/cli_config.py", line 49, in command
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/cli.py", line 116, in wrapper
    return f(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 483, in task_run
    task_return_code = _run_task_by_selected_method(args, _dag, ti)
                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 256, in _run_task_by_selected_method
    return _run_raw_task(args, ti)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/cli/commands/task_command.py", line 341, in _run_raw_task
    return ti._run_raw_task(
           ^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/session.py", line 97, in wrapper
    return func(*args, session=session, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3005, in _run_raw_task
    return _run_raw_task(
           ^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 273, in _run_raw_task
    TaskInstance._execute_task_with_callbacks(
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3159, in _execute_task_with_callbacks
    result = self._execute_task(context, task_orig)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 3183, in _execute_task
    return _execute_task(self, context, task_orig)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 767, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 733, in _execute_callable
    return ExecutionCallableRunner(
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 422, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 238, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 256, in execute_callable
    return runner.run(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/utils/operator_helpers.py", line 252, in run
    return self.func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/spaceflight_data_ingest_v2.py", line 128, in fetch_blogs
    blogs = data['blogs']
            ~~~~^^^^^^^^^
KeyError: 'blogs'
[2025-01-17T20:57:06.745+0000] {local_task_job_runner.py:266} INFO - Task exited with return code 1
[2025-01-17T20:57:06.762+0000] {taskinstance.py:3895} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-01-17T20:57:06.765+0000] {local_task_job_runner.py:245} INFO - ::endgroup::
